version: "2"
run:
  go: "1.17"
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - err113
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Digital_Shane/treeview/extensions/s3
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
